//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMRCOG
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChatUser
    {
        public int CHAT_USER_ID { get; set; }
        public string CHAT_USERNAME { get; set; }
        public string CHAT_USER_EMAIL { get; set; }
        public string CHAT_USER_IMAGE { get; set; }
        public string CHAT_USER_PASSWORD { get; set; }
        public int CHAT_ROLE_ID { get; set; }
        public int CHAT_STATUS_ID { get; set; }
        public string CONNECTION_ID { get; set; }
        public bool IsEmailConfirmed { get; set; }
        public string IP { get; set; }
        public string COUNTRY { get; set; }
        public int CRTD_BY { get; set; }
        public System.DateTime CRTD_DATE { get; set; }
        public int UPDT_BY { get; set; }
        public System.DateTime UPDT_DATE { get; set; }
        public bool IsActiveChat { get; set; }
        public bool IsActive { get; set; }
    }
}
