//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMRCOG
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCourse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCourse()
        {
            this.tblCourseDetails = new HashSet<tblCourseDetail>();
            this.tblCourseModules = new HashSet<tblCourseModule>();
            this.tblCoursePackages = new HashSet<tblCoursePackage>();
            this.tblUserModuleSubscriptions = new HashSet<tblUserModuleSubscription>();
        }
    
        public int COURSE_ID { get; set; }
        public string COURSE_NAME { get; set; }
        public string COURSE_IMAGE { get; set; }
        public Nullable<System.DateTime> COURSE_START_DATE { get; set; }
        public Nullable<System.DateTime> COURSE_END_DATE { get; set; }
        public Nullable<int> COURSE_TYPE_ID { get; set; }
        public Nullable<System.DateTime> CRTD_DATE { get; set; }
        public Nullable<int> CRTD_BY { get; set; }
        public Nullable<System.DateTime> UPDT_DATE { get; set; }
        public Nullable<int> UPDT_BY { get; set; }
        public bool IsActive { get; set; }
    
        public virtual tblCourseType tblCourseType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCourseDetail> tblCourseDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCourseModule> tblCourseModules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCoursePackage> tblCoursePackages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserModuleSubscription> tblUserModuleSubscriptions { get; set; }
    }
}
