//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMRCOG
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChatRole
    {
        public int CHAT_ROLE_ID { get; set; }
        public string ROLE_NAME { get; set; }
        public int CRTD_BY { get; set; }
        public System.DateTime CRTD_DATE { get; set; }
        public int UPDT_BY { get; set; }
        public System.DateTime UPDT_DATE { get; set; }
        public bool IsActive { get; set; }
    }
}
