//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMRCOG
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChatOLD
    {
        public int ID { get; set; }
        public int USER_ID { get; set; }
        public int ADMIN_ID { get; set; }
        public bool isAdmin { get; set; }
        public string CHAT { get; set; }
        public System.DateTime CRTD_TIME { get; set; }
        public string CONNECTION_ID { get; set; }
        public string URL { get; set; }
        public string SCROLEPOSITION { get; set; }
        public string PLATFORM { get; set; }
        public string LANGUAGE { get; set; }
        public string BROWSER { get; set; }
        public string IP { get; set; }
    }
}
