//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMRCOG
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChat
    {
        public int CHAT_ID { get; set; }
        public int CHAT_USER_ID { get; set; }
        public string CONNECTION_ID { get; set; }
        public string SESSION_ID { get; set; }
        public string TEXT { get; set; }
        public string URL { get; set; }
        public string SCROLEPOSITION { get; set; }
        public string PLATFORM { get; set; }
        public string LANGUAGE { get; set; }
        public string BROWSER { get; set; }
        public string COUNTRY { get; set; }
        public string CITY { get; set; }
        public string IP { get; set; }
        public System.DateTime CRTD_DATE { get; set; }
        public bool IsVisibleToUser { get; set; }
        public bool isAdmin { get; set; }
    }
}
