//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMRCOG
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvent
    {
        public int EVENT_ID { get; set; }
        public string HEADING { get; set; }
        public string EVENT_IMAGE { get; set; }
        public System.DateTime START_DATE_TIME { get; set; }
        public System.DateTime END_DATE_TIME { get; set; }
        public string SHORT_DESCRIPTION { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime CRTD_DATE { get; set; }
        public int CRTD_BY { get; set; }
        public Nullable<System.DateTime> UPDT_DATE { get; set; }
        public Nullable<int> UPDT_BY { get; set; }
        public bool IsActive { get; set; }
    }
}
