//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMRCOG
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string IMAGE { get; set; }
        public string DESCRIPTION { get; set; }
        public string DETAIL { get; set; }
        public decimal STRIKE_PRICE { get; set; }
        public decimal PRICE { get; set; }
    }
}
