//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMRCOG
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuizProgress
    {
        public int QUIZ_PROGRESS_ID { get; set; }
        public int USER_ID { get; set; }
        public int QUIZ_ID { get; set; }
        public System.DateTime TIME_SPENT { get; set; }
        public int QUIZ_RESULT { get; set; }
        public int QUIZ_ATTEMPT { get; set; }
        public Nullable<int> CRTD_BY { get; set; }
        public Nullable<System.DateTime> CRTD_DATE { get; set; }
        public Nullable<int> UPDT_BY { get; set; }
        public Nullable<System.DateTime> UPDT_DATE { get; set; }
        public bool IsActive { get; set; }
    
        public virtual tblQuize tblQuize { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
