//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMRCOG
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReview
    {
        public int REVIEW_ID { get; set; }
        public string REVIEW_HEADING { get; set; }
        public string REVIEW_DESCRIPTION { get; set; }
        public string STUDENT_NAME { get; set; }
        public string STUDENT_TITLE { get; set; }
        public string STUDENT_IMAGE { get; set; }
        public Nullable<System.DateTime> CRTD_DATE { get; set; }
        public Nullable<int> CRTD_BY { get; set; }
        public Nullable<System.DateTime> UPDT_DATE { get; set; }
        public Nullable<int> UPDT_BY { get; set; }
        public bool IsActive { get; set; }
    }
}
