//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMRCOG
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTopicUnitsQuize
    {
        public int TOPIC_UNITS_QUIZES_ID { get; set; }
        public int TOPIC_ID { get; set; }
        public Nullable<int> UNIT_ID { get; set; }
        public Nullable<int> QUIZ_ID { get; set; }
        public int TOPIC_UNITS_SORTORDER { get; set; }
        public Nullable<int> CRTD_BY { get; set; }
        public Nullable<System.DateTime> CRTD_DATE { get; set; }
        public Nullable<int> UPDT_BY { get; set; }
        public Nullable<System.DateTime> UPDT_DATE { get; set; }
        public bool IsActive { get; set; }
    
        public virtual tblQuize tblQuize { get; set; }
        public virtual tblTopic tblTopic { get; set; }
        public virtual tblUnit tblUnit { get; set; }
    }
}
